[tool.black]
line-length = 100
exclude = "migrations/*"

[tool.isort]
skip_glob = "**/migrations/*.py"
multi_line_output = 3
known_django = "django"
known_djangocontrib =" django.contrib"
sections = "FUTURE,STDLIB,DJANGO,DJANGOCONTRIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
