
Resources:
  searchRxBucket:
    Type: AWS::S3::Bucket


  bucketName:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: s3_bucket
      Type: String
      Value: !Ref searchRxBucket

  bucketName:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: cfn_bucket
      Type: String
      Value: !Ref searchRxBucket

Outputs:
  bucketname:
    Value: !Ref searchRxBucket
