# Generated by Django 4.0.2 on 2022-05-03 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0003_mylabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Drug_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drug_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.druglabel')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='save_drug_label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
