# Generated by Django 4.0.2 on 2022-05-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_save_drug_label_remove_user_saved_posts_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_drug_label',
            name='date',
        ),
    ]
