name: linting style check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: 'pip'
          cache-dependency-path: '**/dle/requirements.txt'
      - name: Install deps using Pip
        run: pip install -r requirements-dev.txt
        if: steps.python-cache.outputs.cache-hit != 'true'
      - name: Run isort
        run: isort dle --check
      - name: Run black
        run: black dle --check --diff
      - name: Run flake8
        run: flake8 dle
