name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.7.3'
          mysql user: 'dle_user'
          mysql password: 'uDyvfMXHIKCJ'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dle/requirements.txt
      - name: Run Tests
        run: |
          cd dle && python manage.py test
